### PR TITLE
Add AUR package

### PR DESCRIPTION
**Pull request by jneidel**
I created an [AUR pkg](https://aur.archlinux.org/packages/portal-bin)

### CODE REVIEW

**Comment by ZinoKader** [comment]
Nice, thank you! I will merge this once it is set up in the release pipeline as well.

**Comment by ZinoKader** [comment]
Thank you again, and sorry for the long wait. As part of a larger readme refresh, this is included in the README. Is it possible to get the package name "portal" in the AUR repository, when installing the package?

**Comment by jneidel** [comment]
> Is it possible to get the package name "portal" in the AUR repository

The `-bin` postfix specifies that the package uses a binary release (from github.)

The `portal` package without the `bin` would be expected to build the binary itself.

I like doing the `-bin` packages more, as I don't have do deal with build dependencies and the underlyings of the application :smile:

**Comment by ZinoKader** [comment]
> As per AUR convention, the `-bin` postfix specifies that the package uses a binary release (from github.)

Ah! I'm not on Arch as you can guess and did not know that. We'll follow the conventions, of course. Thanks :)

**Pull request merged**
